name: windows-ci
env:
  BUILD_DIR: build
  CONFIG_TYPE: Release
on:
  push:
    paths:
      - '.github/workflows/windows-ci.yml'
      - 'src/**.cpp'
      - 'include/**.h'
      - 'CMakeLists.txt'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get cmake
      uses: lukka/get-cmake@v3.21.1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Cache vcpkg
      uses: actions/cache@v3
      env:
        cache-name: cache-vcpkg
      with:
        path: .\vcpkg
        key: vcpkg_deps-${{ hashFiles('.vcpkg_deps.txt') }}

    - name: Setup vcpkg
      run: |
        if ((Get-ChildItem vcpkg | Measure-Object).Count -eq 0) {
          git submodule update --init vcpkg
        }
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies
      run: .\vcpkg\vcpkg.exe install --triplet=x64-windows "@.vcpkg_deps.txt"

    - name: Run cmake
      run: cmake.exe -DCMAKE_CONFIGURATION_TYPES="$env:CONFIG_TYPE" -S . -B $env:BUILD_DIR

    - name: Build library
      run: MSBuild.exe $env:BUILD_DIR\gbe.sln /target:libgbe

    - name: Upload library artifact
      uses: actions/upload-artifact@v3
      with:
        name: libgbe.lib
        path: ${{ env.BUILD_DIR }}/${{ env.CONFIG_TYPE }}/gbe.lib

    - name: Build executable
      run: MSBuild.exe $env:BUILD_DIR\gbe.sln /target:gbe
